FROM python:3.11-slim

WORKDIR /app

# 1. Install dependencies (using piwheels for ARM as requested)
COPY requirements.txt .
RUN pip install --no-cache-dir --extra-index-url https://www.piwheels.org/simple -r requirements.txt

# 2. Copy the Web App (dist folder) - Generated by GitHub Action
COPY dist ./dist

# 3. Copy the rest of the repo (optional, if we want to run scripts later)
COPY . .

# 4. Serve the Web App for Mobile Access
# Using Python's built-in HTTP server to serve the static React files
EXPOSE 80
CMD ["python", "-m", "http.server", "80", "--directory", "dist"]
